// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhjnTZa3r-WpIHRrJiQbULwa4D8FaKKac',
    appId: '1:720887804894:web:f967006d203bd33b90e34f',
    messagingSenderId: '720887804894',
    projectId: 'flutterpushnotification-a4ed6',
    authDomain: 'flutterpushnotification-a4ed6.firebaseapp.com',
    storageBucket: 'flutterpushnotification-a4ed6.appspot.com',
    measurementId: 'G-NGNT5THMN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJQ3H-LKYhQ_-JFTqahASIq9--fm92H4s',
    appId: '1:720887804894:android:dbbe3e930aec67fb90e34f',
    messagingSenderId: '720887804894',
    projectId: 'flutterpushnotification-a4ed6',
    storageBucket: 'flutterpushnotification-a4ed6.appspot.com',
  );
}
